/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LogicContract__factory } from "./LogicContract__factory";
export { TokenERC20__factory } from "./TokenERC20__factory";
